### ISSUE TITLE
UnboundLocalError: local variable 'X_predict' referenced before assignment

### ISSUE THREAD

**Issue by ghost** [mtobeiyf/audio-classification#8]
The following is the error I have encountered. Could you please guide me out of it?

**Traceback (most recent call last):
  File "cnn.py", line 139, in <module>
    main(args)
  File "cnn.py", line 125, in main
    elif args.predict: predict(args)
  File "cnn.py", line 88, in predict
    X_predict = np.expand_dims(X_predict, axis=2)
UnboundLocalError: local variable 'X_predict' referenced before assignment**

**Comment by ZhongLIFR** [comment]
I got two errors when executing the file "cnn.py".
1. Unresolved reference 'feat_extract' when we define the function:train(args).
solution for this error: we should use "import feat_extract" instead of using "from feat_extract import *";
2.Unresolved reference 'X_predict' when we define the function: predict(args).
"X_predict = np.expand_dims(X_predict, axis=2)", the "X_predict" in the right side is not pre-defined nor pre-produced.
solution for this error: not found yet.

**Comment by imfing** [comment]
@ZhongLIFR @raifofcl  I'll check them out.

**Comment by imfing** [comment]
The errors are fixed now.
